os:
- linux
cache:
  directories:
  - "$HOME/.composer/cache"
language: php
php:
- 7.2
install:
- composer install
script:
- phpunit --configuration phpunit.xml --coverage-text
deploy:
  provider: azure_web_apps
  verbose: true
  on:
    tags: true
notifications:
  email:
    recipients: oskar1.katra@gmail.com, robin.lars.hakansson@gmail.com